--- 
author: 'Simone Brazzi'
date: '2026-01-09'
engine: jupyter 
title: '03 Hyperparameter Optimization with Optuna'
execute:
  eval: true
theme:
  dark: darkly
  light: flatly
--- 

# 1. Theory

Evolution of the Bayesian Search, which exclude a priori part of the hyperparameter space BEFORE the fit. It is particularly useful with big hyperparameter spaces.
It uses a **Tree structured parzen estimator** cycle:
- **Objective function**: function that takes hyperparameters as input and return a metric to minimize/maximize.
- Define a **parameter distribution**.
- **Likelihood estimation**: two probability density functions are built, one for good trials and one for bad trials.
- **Probabilistic model** based on the 2 probability density functions. One is cutted off if the result is a low performance.
- **Future trials** are selected by maximizing the **Expected Improvement**.

$$
P(y | x, \theta) 
$$

- **Dynamic search** in a binded hyperparameter space.
- **Pruning** of not promising trials during the training.
  - PROS: curvesomputationally efficient.
  - PROS: Flexilbility.
  - CONS: pruning too strong with simple problems.
  - CONS: Steeper learning curves.
- sklearn approach and ease of integration with other libraries.

# 2. Practice

```{python}
import matplotlib.pyplot as plt
import optuna 
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.svm import SVC 
import numpy as np 

def optuna_classification(x, y, cv, n_trials):

  # n_trials = max number of trials so there is an upper limit to exit the study

  xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

  def objective(trial):

    C = trial.suggest_float("C", 1e-10, 1e+10, log=True)
    gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])
    kernel = trial.suggest_categorical('kernel', ['linear', 'poly', 'rbf', 'sigmoid'])

    model = SVC(C=C, gamma=gamma, kernel=kernel, probability=True, random_state=42)
    score = cross_val_score(model, xtrain, ytrain, cv=cv, scoring='accuracy').mean()

    return score

  study = optuna.create_study(direction='maximize', study_name='study 1', sampler=optuna.samplers.TPESampler(seed=42))
  study.optimize(objective, n_trials=n_trials)
  best_params = study.best_params
  best_model = SVC(C=best_params['C'], gamma=best_params['gamma'], kernel=best_params['kernel'], probability=True, random_state=42)
  best_model.fit(xtrain, ytrain)

  ytrain_pred = best_model.predict(xtrain)
  ytest_pred = best_model.predict(xtest)
  train_accuracy = accuracy_score(ytrain, ytrain_pred)
  test_accuracy = accuracy_score(ytest, ytest_pred)

  print(f"best params: {best_params}")
  print(f"train accuracy: {train_accuracy:.4f}")
  print(f"test accuracy: {test_accuracy:.4f}")

  study_accuracies = [trial.value for trial in study.trials]
  plt.plot(study_accuracies)
  plt.xlabel("Trial Number")
  plt.ylabel("Accuracy")
  plt.title("Accuracy by Trial Number")
  plt.show()

  return best_model

```


```{python}

iris = load_iris()
x, y = iris.data, iris.target

best_classifier = optuna_classification(x, y, cv=5, n_trials=50)
```

# 3. Exercise

Compare all the classic method with the modern one and test the time.


```{python}
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split, cross_val_score, cross_validate, GridSearchCV, RandomizedSearchCV
from sklearn.svm import SVR
from skopt import BayesSearchCV
import optuna
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
from time import time
import matplotlib.pyplot as plt

diabetes = load_diabetes()
x, y = diabetes.data, diabetes.target

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=.2, random_state=42)

```
## Grid Search

```{python}
def make_grid_search(x, y, cv, grid):
  tic = time()

  svr = SVR()
  grid_search = GridSearchCV(
    estimator=svr,
    param_grid=grid,
    scoring='r2',
    n_jobs=-1,
    cv=cv
  )

  grid_search.fit(xtrain, ytrain)

  best_params = grid_search.best_params_
  best_model = grid_search.best_estimator_
  best_score = grid_search.best_score_

  ytest_pred = grid_search.predict(xtest)
  r2_test = r2_score(ytest, ytest_pred)

  print(f"Best params: {best_params}.")
  print(f"Best model: {best_model}.")
  print(f"Best R2-score: {r2_test}.")
  print(f"Time elapsed: {time() - tic :.4f} seconds.")

  return

grid = {
  "C": [0.1, 1, 10, 100],
  "gamma": ["scale", "auto"],
  "kernel": ["linear", "rbf", "poly", "sigmoid"],
  "tol" : [.0001, .001, .01, .1]
}

make_grid_search(x, y, cv=7, grid=grid)
```

## Random Search

```{python}
def make_random_search(x, y, cv, grid, n_iter):

  tic = time()

  svr = SVR()
  grid_search = RandomizedSearchCV(
    estimator=svr,
    param_distributions=grid,
    n_iter=n_iter,
    scoring='r2',
    cv=cv,
    return_train_score=True
  )

  grid_search.fit(xtrain, ytrain)

  best_params = grid_search.best_params_
  best_model = grid_search.best_estimator_
  best_score = grid_search.best_score_

  ytest_pred = grid_search.predict(xtest)
  r2_test = r2_score(ytest, ytest_pred)

  print(f"Best params: {best_params}.")
  print(f"Best model: {best_model}.")
  print(f"Best test R2-score: {r2_test}.")
  print(f"Time elapsed: {time() - tic :.4f} seconds.")

  return

make_random_search(x, y, cv=7, grid=grid, n_iter=20)
```

```{python}
def bayesian_search_classification(x, y, cv, search_space, n_iter):
    
    tic = time()
    model = SVR()
    bayes_search = BayesSearchCV(
        model,
        search_space,
        n_iter=n_iter,
        cv=cv,
        scoring="r2",
        return_train_score=True,
        random_state=42
    )
    bayes_search.fit(xtrain, ytrain)

    best_model = bayes_search.best_estimator_
    best_params = bayes_search.best_params_
    best_score = bayes_search.best_score_

    ytest_pred = best_model.predict(xtest)
    r2_score_test = r2_score(ytest, ytest_pred)

    print(f'best Hyperparameters: {best_params}')
    print(f'best Accuracy: {100 * best_score:.2f}%')
    print(f'best Test R2-score: {100 * r2_score_test:.2f}%')
    print(f"Time elapsed: {time() - tic :.4f} seconds.")

    return

search_space = {
    'C' : (1e-6, 1e+6, 'log-uniform'), # distribution
    'gamma' : ( 'scale', 'auto' ),
    'kernel' : ( 'linear', 'rbf', 'poly', 'sigmoid' )
}

bayesian_search_classification(x, y, cv=5, search_space=search_space, n_iter=20)
```

## Optuna


```{python}
def make_optuna(cv, n_trials):

  tic = time()

  def objective(trial):

    C = trial.suggest_float("C", 1e-10, 1e+10, log=True)
    gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])
    kernel = trial.suggest_categorical('kernel', ['linear', 'poly', 'rbf', 'sigmoid'])

    svr = SVR(C=C, gamma=gamma, kernel=kernel, max_iter=10000)
    score = cross_val_score(
      estimator=svr,
      X=xtrain,
      y=ytrain,
      scoring='r2',
      cv=cv
    ).mean()

    return score

  study = optuna.create_study(
    direction="maximize",
    study_name= "study_comparison",
    sampler=optuna.samplers.TPESampler(seed=42)
  )
  study.optimize(objective, n_trials=n_trials)

  best_params = study.best_params
  best_model = SVR(
    C=best_params["C"],
    gamma=best_params["gamma"],
    kernel=best_params["kernel"]
  )
  best_model.fit(xtrain, ytrain)


  ytrain_pred = best_model.predict(xtrain)
  ytest_pred = best_model.predict(xtest)
  train_accuracy = r2_score(ytrain, ytrain_pred)
  test_accuracy = r2_score(ytest, ytest_pred)

  print(f"best params: {best_params}")
  print(f"train accuracy: {train_accuracy:.4f}")
  print(f"test accuracy: {test_accuracy:.4f}")
  print(f"Elapsed time: {time() - tic :.4f}.")

  study_scores = [trial.value for trial in study.trials]
  plt.plot(study_scores)
  plt.xlabel("Trial Number")
  plt.ylabel("R2 score")
  plt.title("R2 Score by Trial Number")
  plt.show()

  return best_model

make_optuna(cv=7, n_trials=20)
print("Optuna finished!")
```
